BankMVC/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BankMVC.Models
{
    public class Customer
    {
        public virtual int Id { get; set; }

        public virtual string FirstName { get; set; }

        public virtual string LastName { get; set; }

        public virtual long ContactNo { get; set; }

        public virtual string Email { get; set; }

        public virtual User User { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual ISet<Document> Documents { get; set; }

        public virtual ISet<Account> Accounts { get; set; }

        public Customer()
        {
            Documents = new HashSet<Document>();
           Accounts = new HashSet<Account>();

        }
    }
}

BankMVC/Controllers/CustomerController.cs
using BankMVC.Assemblers;
using BankMVC.Models;
using BankMVC.Services;
using BankMVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankMVC.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        // GET: Customer

        private ICustomerService _customerService;
        private CustomerAssembler _customerAssembler;
        private IUserService _userService;
        private UserAssembler _userAssembler;
        public CustomerController(ICustomerService customerService, CustomerAssembler customerAssembler, IUserService userService, UserAssembler userAssembler)
        {
            _customerService = customerService;
            _customerAssembler = customerAssembler;
            _userService = userService;
            _userAssembler = userAssembler;
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var customers = _customerService.GetAll();
            var customerVMs = customers.Select(c => _customerAssembler.ConvertToViewModel(c)).ToList();
            return View(customerVMs);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult AdminDashboard()
        {
            return View();
        }
        [Authorize(Roles = "Customer")]
        public ActionResult CustomerDashboard()
        {
            return View();
        }
        [HttpGet]
        public JsonResult GetData(int page, int rows, string sidx, string sord, string searchString)
        {
            var customers = _customerService.GetAll();

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                int searchId;
                if (int.TryParse(searchString, out searchId))
                {
                    // If the search term is a valid integer, search by Id
                    customers = customers.Where(e => e.Id == searchId).ToList();
                }
                else
                {
                    // If the search term is not an integer, search by other fields
                    customers = customers.Where(e =>
                        e.FirstName.Contains(searchString) ||
                        e.LastName.Contains(searchString) ||
                        e.ContactNo.ToString().Contains(searchString) ||
                        e.Email.Trim().Equals(searchString.Trim(), StringComparison.OrdinalIgnoreCase) ||
                        e.User.Id.ToString().Contains(searchString) ||
                        e.IsActive.ToString().Contains(searchString) ||
                        e.Accounts.Count.ToString().Contains(searchString) ||
                        e.Documents.Count.ToString().Contains(searchString)
                    ).ToList();
                }
            }

            // Get total count of records (for pagination)
            int totalCount = customers.Count();

            // Calculate total pages
            int totalPages = (int)Math.Ceiling((double)totalCount / rows);


            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalCount,
                rows = (from customer in customers
                        orderby sidx + " " + sord
                        select new
                        {
                            cell = new string[] {
                                        customer.Id.ToString(),
                                        customer.FirstName,
                                        customer.LastName,
                                        customer.ContactNo.ToString(),
                                        customer.Email,
                                        customer.User.Username.ToString(),
                                        customer.IsActive.ToString(),
                                        customer.Accounts.Count.ToString(),
                                        customer.Documents.Count.ToString(),
                                        //customer.IsActive?"True":"False",
                                    }
                        }).Skip((page - 1) * rows).Take(rows).ToArray()
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
            //}
            //}

        }
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Create(CustomerVM customerVM)
        {
            if (ModelState.IsValid)
            {
                bool isUnique = _userService.IsUniqueUserName(customerVM.Username);
                if (isUnique)
                {
                    var userVM = new UserVM()
                    {
                        Username = customerVM.Username,
                        Password = customerVM.Password,
                        RoleId = 2
                    };
                    var newUser = _userAssembler.ConvertToModel(userVM);

                    var customer = _customerAssembler.ConvertToModel(customerVM);
                    customer.User = _userService.Add(newUser);

                    var newCustomer = _customerService.Add(customer);
                    ViewBag.Message = "Added Successfully";
                    ViewBag.Status = "Successfull";
                    return View();
                }
                ViewBag.Message = "UserName is not unique";
                ViewBag.Status = "Unsuccessfull";
            }
            return View(customerVM);
        }
        [Authorize(Roles = "Customer")]
        [HttpGet]
        public ActionResult Edit()
        {
            int id = (int)Session["LoginId"];
            var custData = _customerService.GetById(id);
            var custDataVM = _customerAssembler.ConvertToViewModel(custData);
            return View(custDataVM);
        }
        [Authorize(Roles = "Customer")]
        [HttpPost]
        public ActionResult Edit(CustomerVM customerVM)
        {
            ModelState.Remove("Username");
            ModelState.Remove("Password");
            if (ModelState.IsValid)
            {
                var existingCustomer = _customerService.GetById(customerVM.Id);
                if (existingCustomer != null)
                {
                    customerVM.UserId = existingCustomer.User.Id;
                    customerVM.IsActive = true;
                    var updatedCust = _customerAssembler.ConvertToModel(customerVM);
                    _customerService.Update(updatedCust);

                    //return Json(new { success = true, message = "User updated successfully." });
                    ViewBag.Message = "User updated successfully.";
                    ViewBag.Status = "Successfull";
                    return View();
                }

                ViewBag.Message = "No such User Exists";
                ViewBag.Status = "Unsuccessfull";
                //return Json(new { success = false, message = "No such User Exists" });
            }

            return View(customerVM);

        }
        [HttpPost]
        public ActionResult EditByJQGrid(Customer customer)
        {

            var existingCustomer = _customerService.GetById(customer.Id);
            if (existingCustomer != null)
            {
                existingCustomer.FirstName = customer.FirstName;
                existingCustomer.LastName = customer.LastName;
                existingCustomer.Email = customer.Email;
                existingCustomer.ContactNo = customer.ContactNo;
                existingCustomer.Accounts = customer.Accounts;
                _customerService.Update(existingCustomer);

                return Json(new { success = true, message = "User updated successfully." });
            }
            return Json(new { success = false, message = "No such User Exists" });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var existingCustomer = _customerService.GetById(id);
            if (existingCustomer != null)
            {

                _customerService.Delete(existingCustomer);
                //txn.Commit();
                return Json(new { success = true, message = "User deleted successfully." });
            }
            return Json(new { success = false, message = "No such User Exists" });
        }
    }
}

BankMVC/Controllers/DocumentController.cs
using BankMVC.Assemblers;
using BankMVC.Models;
using BankMVC.Services;
using BankMVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankMVC.Controllers
{
    [Authorize]
    public class DocumentController : Controller
    {// GET: User
        private readonly IDocumentService _documentService;
        private readonly DocumentAssembler _documentAssembler;

        public DocumentController(IDocumentService documentService, DocumentAssembler documentAssembler)
        {
            _documentService = documentService;
            _documentAssembler = documentAssembler;
        }

        //public ActionResult Index()
        //{
        //    return View();
        //}
        [Authorize(Roles = "Admin , Customer")]
        [HttpGet]
        public ActionResult Index(string searchString)
        {
            List<Document> documents = new List<Document>();
            if (User.IsInRole("Customer"))
            {
                int tempData = (int)Session["LoginId"];
                documents = _documentService.GetAll().Where(x => x.Customer.Id == tempData).ToList();
            }
            else
            {
                documents = _documentService.GetAll();
                if (!string.IsNullOrEmpty(searchString))
                {
                    documents = documents.Where(d => d.Customer.FirstName.Contains(searchString)).ToList();
                }
            }
            var documentVMs = documents.Select(d => _documentAssembler.ConvertToViewModel(d)).ToList();
            return View(documentVMs);
        }
        [Authorize(Roles = "Customer")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Customer")]
        [HttpPost]
        public ActionResult Create(DocumentVM documentVM, HttpPostedFileBase file)
        {
            ModelState.Remove("CustomerId");
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    documentVM.PostedFile = file;
                    documentVM.CustomerId = (int)Session["LoginId"];
                    var document = _documentAssembler.ConvertToModel(documentVM);
                    var newDocument = _documentService.Add(document);
                    ViewBag.Message = "Added Successfully";
                    ViewBag.Status = "Successfull";
                    //return RedirectToAction("CustomerDashboar", "Customer");
                    return View();
                }
                ViewBag.Message = "Select a file to upload";
                ViewBag.Status = "Unsuccessfull";
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var documentData = _documentService.GetById(id);
            var documentDataVM = _documentAssembler.ConvertToViewModel(documentData);
            return View(documentDataVM);
        }

        [HttpPost]
        public ActionResult Edit(DocumentVM documentVM)
        {
            var document = _documentService.GetById(documentVM.Id);
            if (document != null)
            {
                _documentService.Update(document);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var documentData = _documentService.GetById(id);
            var documentDataVM = _documentAssembler.ConvertToViewModel(documentData);
            return View(documentDataVM);
        }

        [HttpPost]
        public ActionResult Delete(DocumentVM documentVM)
        {
            var document = _documentService.GetById(documentVM.Id);
            if (document != null)
            {
                _documentService.Delete(document);
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin , Customer")]
        [HttpGet]
        public ActionResult ViewDocument(int id, string fileName)
        {
            // Retrieve the document based on the ID
            var document = _documentService.GetById(id);

            if (document != null)
            {
                // Set the Content-Disposition header to "inline" to instruct the browser to display the content
                Response.AppendHeader("Content-Disposition", "inline; filename=" + fileName);

                // Set the content type appropriately based on your document type
                Response.ContentType = "application/pdf"; // Set to "application/pdf" for PDF documents

                // Write the document content to the response stream
                return File(document.DocumentFile, "application/pdf", fileName);
            }
            else
            {
                return HttpNotFound();
            }
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Verify(int id)
        {
            var document = _documentService.GetById(id);
            if (document != null)
            {
                document.IsVerified = true;
                _documentService.Update(document);
            }
            return RedirectToAction("Index");
        }

    }
}

BankMVC/Views/Customer/AdminDashboard.cshtml
@{
    ViewBag.Title = "Admin Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        background-color: #f0f0f0;
    }

    .container {
        margin-top: auto;
    }

    h2 {
        text-align: center;
        color: #3498db;
        font-size: 2em;
        margin-bottom: 20px;
    }

    .dashboard-container {
        display: flex;
        justify-content: space-around;
        flex-wrap: wrap;
    }

    .card {
        width: 250px;
        padding: 30px;
        margin: 15px;
        border: 2px solid #3498db;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        background-color: #fff;
        font-size: 1.5em;
        text-align: center;
    }

        .card h2 {
            color: #3498db;
            font-size: large;
        }

        .card p {
            margin-top: 15px;
            color: #333;
            font-size: large;
        }

    .card-button {
        display: block;
        margin-top: 20px;
        text-align: center;
        font-size: large;
    }

    .btn-primary {
        background-color: #3498db;
        border-color: #3498db;
    }

        .btn-primary:hover {
            background-color: #2a80b9;
            border-color: #2a80b9;
        }
</style>

<div class="container">
    <h2>Welcome, @Session["User"]!</h2>

    <br />
    <div class="dashboard-container">
        <!-- Card 1 -->
        <div class="card">
            <h2>Transactions</h2>
            <p><label>Check Transactions info:</label> </p>
            @Html.ActionLink("View Transactions", "Index", "Transaction", null, new { @class = "card-button btn btn-primary" })
        </div>

        <!-- Card 2 -->
        <div class="card">
            <h2>Accounts</h2>
            <p><label>Check Accounts info:</label></p>
            @Html.ActionLink("View Account", "Index", "Account", null, new { @class = "card-button btn btn-primary" })
        </div>

        <!-- Card 3 -->
        <div class="card">
            <h2>Documents</h2>
            <p><label>Check Documents info:</label> </p>
            @Html.ActionLink("View Document", "Index", "Document", null, new { @class = "card-button btn btn-primary" })
        </div>


    </div>
</div>
<br />
<br />
<br />

@section Scripts {
    <!-- Add your scripts if needed -->
}

BankMVC/Views/Customer/Create.cshtml
@model BankMVC.ViewModels.CustomerVM

@{
    ViewBag.Title = "Customer Registration";
}
@{
    if (ViewBag.Message != null)
    {
        <script>
                 alert("@ViewBag.Message")

        </script>
    }

    if (ViewBag.Status == "Successfull")
    {
        if (User.Identity.IsAuthenticated)
        {
            <script>

            window.onload = () => {
                window.location.href ='@Url.Action("AdminDashboard", "Customer")';
            };
            </script>

        }
        else
        {
            <script>

                 window.onload = () => {
                     window.location.href ='@Url.Action("Login", "Login")';
                 };
            </script>

        }
    }
}

<style>
    body {
        background-color: #f5f5f5;
        color: #333;
    }

    .container {
        margin-top: auto;

    }

    .register-container {
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin: 20px;
        resize:horizontal;
    }

    .register-header {
        text-align: center;
        color: #3498db;
        font-size: 28px;
        font-weight: bold;
        margin-bottom: 20px;
    }

    .form-horizontal {
        margin-top: 20px;
    }

    .control-label {
        /*color: #333;*/
        /*font-size: large;*/
        color: #3498db;
        font-weight: bold;
        flex: 1;
        /*padding-right:40px;*/
        padding-left: 40px;
    }

    .form-control {
        /*height: 40px;
        font-size: large;*/
        height: 40px;
        font-size: large;
        flex: 2;
        margin-left: 12px;
    }

    .btn-default {
        background-color: #3498db;
        color: #fff;
        border-color: #3498db;
        font-size: large;
        margin-right: 15px
    }

        .btn-default:hover {
            background-color: #2a80b9;
            border-color: #2a80b9;
        }

    .btn-danger {
        background-color: #d9534f;
        border-color: #d9534f;
        font-size: large;
    }

        .btn-danger:hover {
            background-color: #c9302c;
            border-color: #c9302c;
        }
</style>

<div class="container">
    <div class="row ">
        <div class="col-md-6 col-md-offset-3 mx-auto register-container">
            <div class="register-header">Register</div>
            <hr />

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <!-- Repeat the similar structure for other form fields -->

                    <div class="form-group">
                        @*<span class = "control-label ">First Name</span>*@
                        @Html.LabelFor(model => model.FirstName,"First Name", htmlAttributes: new { @class = "control-label col-md-4" })

                        <div class="col-md-8 ">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LastName, "Last Name", htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ContactNo, "Contact No", htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2  col-md-10" align="center">
                            <input type="submit" value="Create" class="btn btn-default" />

                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@if (!User.Identity.IsAuthenticated)
{
    <div align="right">
        @Html.ActionLink("Login", "Login", "Login", new { area = "" }, new { @class = "btn btn-danger" })
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankMVC/Views/Customer/CustomerDashboard.cshtml
@{
    ViewBag.Title = "Customer Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        background-color: #f0f0f0; /* Set your preferred background color */
    }

    .container {
        margin-top: auto;
    }

    h2 {
        text-align: center;
        color: #3498db;
        font-size: 2em;
        margin-bottom: 20px;
    }

    .dashboard-container {
        display: flex;
        justify-content: space-around;
        flex-wrap: wrap;
    }

    .card {
        width: 250px;
        padding: 30px;
        margin: 15px;
        border: 2px solid #3498db; /* Border color matches h2 color for consistency */
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        background-color: #fff;
        font-size: 1.5em;
        text-align: center;
    }

        .card h2 {
            color: #3498db;
            font-size: large;
        }

        .card p {
            margin-top: 15px;
            color: #333;
            font-size: large;
        }

    .card-button {
        display: block;
        margin-top: 20px;
        text-align: center;
        font-size: large;
    }

    .btn-primary {
        background-color: #3498db;
        border-color: #3498db;
    }

        .btn-primary:hover {
            background-color: #2a80b9;
            border-color: #2a80b9;
        }
</style>

<div class="container">
    <h2>Welcome, @Session["User"]!</h2>
    <br />
    <div class="dashboard-container">
        <!-- Card 1 -->
        <div class="card">
            <h2>Passbook</h2>
            <p><label>Check Passbook info:</label> </p>
            @Html.ActionLink("View Passbook", "Index", "Transaction", null, new { @class = "card-button btn btn-primary" })
        </div>

        <!-- Card 2 -->
        <div class="card">
            <h2>Accounts</h2>
            <p><label>Check Account info:</label></p>
            @Html.ActionLink("View Account", "Index", "Account", null, new { @class = "card-button btn btn-primary" })
        </div>

        <!-- Card 3 -->
        <div class="card">
            <h2>Documents</h2>
            <p><label>Check Document info:</label> </p>
            @Html.ActionLink("View Document", "Index", "Document", null, new { @class = "card-button btn btn-primary" })
        </div>

        
    </div>
</div>
<br />
<br />
<br />

@section Scripts {
    <!-- Add your scripts if needed -->
}

BankMVC/Views/Customer/Edit.cshtml
@model BankMVC.ViewModels.CustomerVM

@{
    ViewBag.Title = "Edit";
}
@{
    if (ViewBag.Message != null)
    {
        <script>
                 alert("@ViewBag.Message")

        </script>
    }

    if (ViewBag.Status == "Successfull")
    {
            <script>

            window.onload = () => {
                window.location.href ='@Url.Action("CustomerDashboard", "Customer")';
            };
            </script>

        
    }
}
<style>
    body {
        background-color: #f5f5f5;
        color: #333;
    }

    .container {
        margin-top: auto;
    }

    .register-container {
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin: 20px;
    }

    .register-header {
        text-align: center;
        color: #3498db;
        font-size: 28px;
        font-weight: bold;
        margin-bottom: 20px;
    }

    .form-horizontal {
        margin-top: 20px;
    }

    .control-label {
        /*color: #333;*/
        /*font-size: large;*/
        color: #3498db;
        font-weight: bold;
        flex: 1;
        padding-left: 40px;
    }

    .form-control {
        /*height: 40px;
        font-size: large;*/
        height: 40px;
        font-size: large;
        flex: 2;
        margin-left: 12px;
    }

    .btn-default {
        background-color: #3498db;
        color: #fff;
        border-color: #3498db;
        font-size: large;
        margin-right: 15px
    }

        .btn-default:hover {
            background-color: #2a80b9;
            border-color: #2a80b9;
        }

    .btn-danger {
        background-color: #d9534f;
        border-color: #d9534f;
        font-size: large;
    }

        .btn-danger:hover {
            background-color: #c9302c;
            border-color: #c9302c;
        }
</style>

<div class="container">
    <div class="row ">
        <div class="col-md-6 col-md-offset-3 mx-auto register-container">
            <div class="register-header">Update Profile</div>
            <hr />

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <!-- Repeat the similar structure for other form fields -->

                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName,"First Name", htmlAttributes: new { @class = "control-label col-md-4" })

                        <div class="col-md-8 ">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LastName ,"Last Name", htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ContactNo,"Contact No", htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-offset-2  col-md-10" align="center">
                            <input type="submit" value="Submit" class="btn btn-default" />

                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}